# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master", "dev" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref_name == 'master'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Build <and Publish>
        run: |
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p dckr_pat_1OUT__NJyc3StMSjGR1gQt88Af4
          docker build -t julianwerner/robocup-backend .
          echo "Finish building"
          docker push julianwerner/robocup-backend 
            
          
    
